version: '3'

services:
  web:
    build: .
    image: yektanet_web
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000 --noreload"
    volumes:
      - .:/app
    ports:
      - "8020:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - db

  db:
    container_name: yektanet_postgres
    image: postgres
    env_file:
      - db.env
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - "5435:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      timeout: 1s
      retries: 3

  redis:
    image: redis:7-alpine

  celery_worker:
    build: .
    image: celery
    command: celery -A url_shortener.celery worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - web
      - db

  celery_beat:
    build: .
    image: celery_beat
    command: celery -A url_shortener.celery beat -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db

volumes:
  db_data: